### ISSUE TITLE
Bug: Bitbucket projects not all listed.

### ISSUE THREAD

**Issue by spydmobile** [adamjimenez/shiftedit#121]
When I create a new site and try and connect to my bitbucket project it shows me only 10 of my 50 repos on BB.

**Comment by adamjimenez** [comment]
I've pushed an update - please let me know if that fixes it for you.

**Comment by spydmobile** [comment]
Wow - Fast! Yes I see them all, but cannot really connect, when i press the connect button it says - no password. if I save it and try and open it, its says: 
Cannot connect to smartmap-XXXXXX.box.shiftedit.net:XXXXXX. Error 111. Connection refused
Can't connect with key
XXX = id and ports.

**Comment by adamjimenez** [comment]
The env is up and running. Try re-selecting the project name from the project dropdown in the left hand panel.

**Comment by spydmobile** [comment]
Hmm, Still broken, but now I can work around:
ok, if I create new and connect it fails with - no password, 
if I create new and Save, it saves, tries to connect and fails with "cannot connect to....."
if i click ok on the error, then change the site dropdown and rechoose, it connects.
Getting closer Adam :)

**Comment by adamjimenez** [comment]
Yes, this makes sense as the container needs some time to start. I will
look at this.

On 9 February 2016 at 23:12, Franco Nogarin <notifications@github.com>
wrote:

> Hmm, Still broken, but now I can work around:
> ok, if I create new and connect it fails with - no password,
> if I create new and Save, it saves, tries to connect and fails with
> "cannot connect to....."
> if i click ok on the error, then change the site dropdown and rechoose, it
> connects.
> Getting closer Adam :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/121#issuecomment-182128295>
> .
>



-- 
Best regards,
Adam Jimenez

**Comment by adamjimenez** [comment]
A couple of tweaks for this. I've increased the time-out to allow the container more time to start up.
Also the refresh button will now re-connect to the server instead of just refreshing the file tree.

**Comment by spydmobile** [comment]
Odd, I am not sure why but even when I log out and start from scratch I still see these errors, workaround works fine, but in the name of debugging, I am not seeing anything helpful I am afraid.

**Comment by adamjimenez** [comment]
I know what's happening I just don't have a good way of tracking the initial deployment status right now. Instead of changing the site you will be able to just click the refresh icon after this update.

**Comment by adamjimenez** [comment]
This will work better in the next update where it will wait for the SSH process to start before trying to connect.
